export const FETCH_DATA_REQUEST = 'DATA_REQUEST/FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'DATA_REQUEST/FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'DATA_REQUEST/FETCH_DATA_AILURE';
