export const FETCH_PRODUCTLIST_START = 'FETCH_PRODUCTLIST_START';
export const FETCH_PRODUCTLIST_END = 'FETCH_PRODUCTLIST_END';
export const FETCH_PRODUCTLIST_SUCCESS = 'FETCH_PRODUCTLIST_SUCCESS';
export const FETCH_PRODUCTLIST_FAILURE = 'FETCH_PRODUCTLIST_FAILURE';

export const FETCH_PRODUCT_ITEM_START = 'FETCH_PRODUCT_ITEM_START';
export const FETCH_PRODUCT_ITEM_END = 'FETCH_PRODUCT_ITEM_END';
export const FETCH_PRODUCT_ITEM_SUCCESS = 'FETCH_PRODUCT_ITEM_SUCCESS';
export const FETCH_PRODUCT_ITEM_FAILURE = 'FETCH_PRODUCT_ITEM_FAILURE';

export const FETCH_CATEGORY_LIST_START = 'FETCH_CATEGORY_LIST_START';
export const FETCH_CATEGORY_LIST_END = 'FETCH_CATEGORY_LIST_END';
export const FETCH_CATEGORY_LIST_SUCCESS = 'FETCH_CATEGORY_LIST_SUCCESS';
export const FETCH_CATEGORY_LIST_FAILURE = 'FETCH_CATEGORY_LIST_FAILURE';

export const UPDATE_PRODUCT_ITEM = 'UPDATE_PRODUCT_ITEM';
export const ADD_PRODUCT_ITEM = 'ADD_PRODUCT_ITEM';
export const DELETE_PRODUCT_ITEM = 'DELETE_PRODUCT_ITEM';
